---
- name: test
  hosts: all
  gather_facts: no
  tasks:
    - name: "1. Init"
      block:
        - name: "test"
          setup:
            gather_subset: "!All"
      rescue:
        - name: "1.1. Error handler"
          include_role:
            name: sample_role
          vars:
            test: "Task: {{ ansible_failed_task.name }}"